### ISSUE TITLE
Cant be pined on Ubuntu dock/Dash to dock GNOME

### ISSUE THREAD

**Issue by tosziro** [OrangeDrangon/android-messages-desktop#158]
Android Messages app cant be pined to dock in GNOME. Could you please fix it?

**Desktop (please complete the following information):**
Ubuntu 20.10 & Fedora 33 (GNOME)

**Comment by OrangeDrangon** [comment]
I will look into this. I am pretty sure i know what you mean by pin to dock but I am spinning up a ubuntu virtual machine as we speak to take a look.

**Comment by tosziro** [comment]
When app its opened I try to click right mouse and chose option "pin to dock" but its not there.

**Comment by OrangeDrangon** [comment]
I am a bit busy for the next few days but I will do my best to get this
fixed.

**Comment by tosziro** [comment]
Great, thanks :-)

**Comment by dhitchcock** [comment]
I had to change the StartupWMClass in the .desktop file
...
StartupWMClass=android-messages-desktop
...

**Comment by tosziro** [comment]
> I had to change the StartupWMClass in the .desktop file
> ...
> StartupWMClass=android-messages-desktop
> ...

Thanks, this resolve issue.
