### ISSUE TITLE
impossible to move window on macOS Catalina and Mojave

### ISSUE THREAD

**Issue by tosziro** [OrangeDrangon/android-messages-desktop#164]
**Describe the bug**
It's impossible to move window on macOS Catalina and Mojave

**To Reproduce**
1. Mouse left click on the bar of application,hold and move mouse.
2. Its not moving

**Expected behavior**
Move application 

**Desktop (please complete the following information):**
 macOS Mojave and Catalina (Propably also Big Sur)

**Comment by sallzt** [comment]
can confirm reproducible on big sur
![recording(1)](https://user-images.githubusercontent.com/18537928/99605399-75178c00-29bc-11eb-8ff7-fbeb25eccaea.gif)

**Comment by OrangeDrangon** [comment]
This seems like a bug with electron. I do not have access to a Mac computer to test though. Once I attempt to fix the other bug in the next day or two electron will version bump and we can see if that fixes it.

**Comment by OrangeDrangon** [comment]
Can I get any feedback on whether or not this is still a problem?

**Comment by plastik46** [comment]
yes it's happening to me also, and i also noticed there is no notification dot on the dock icon.
  
  
  
  
  
Thanks, Josh

**Comment by jasonlyle88** [comment]
Can confirm this issue still exists in 4.3.0

**Comment by manishie** [comment]
Might this help?  https://www.electronjs.org/docs/api/frameless-window#draggable-region

**Comment by bpappin** [comment]
@manishie i think its the native window that's not draggable. Was working for me up until Big Sur.

**Comment by manishie** [comment]
It wasn't working for me on Catalina either.

**Comment by OrangeDrangon** [comment]
I may have fixed this some testers would be appreciated before an official release is created. See the pull request above.

**Comment by manishie** [comment]
@OrangeDrangon thanks!  can try later this evening.
