### ISSUE TITLE
Monochrome Tray Icon

### ISSUE THREAD

**Issue by ceiphr** [OrangeDrangon/android-messages-desktop#166]
**Describe the solution you'd like**
Offer a monochrome tray icon option. This can be a toggle within the electron menubar.

**Describe alternatives you've considered**
https://github.com/bilelmoussaoui/Hardcode-Tray is what I used to use with https://github.com/chrisknepper/android-messages-desktop, but it doesn't work on this fork.

**Additional context**
Discord, Slack, Dropbox, Todoist and Steam all currently use monochrome icons, so this would be great for consistency.

**Comment by OrangeDrangon** [comment]
This should easy and I will definitely look into it.

**Comment by OrangeDrangon** [comment]
Any chance I can get a blue set of these slick icons? Otherwise these feature is ready for merge.

**Comment by ceiphr** [comment]
> Any chance I can get a blue set of these slick icons? Otherwise these feature is ready for merge. @ceiphr

Sure! I'll have to remake them as I ended up deleting the old files. I can do it this weekend.

**Comment by OrangeDrangon** [comment]
Sorry about the delay. There was an issue I considered blocking that I finally completed.

**Comment by ceiphr** [comment]
Sorry for the month-long delay. I remade the icons as I no longer have the old files. Here they are:

https://www.dropbox.com/s/ijfxxxqm606n94u/ms_blue_unread.svg?dl=0
https://www.dropbox.com/s/pfy251vie5kln4y/ms_blue.svg?dl=0

If you need them revised, let me know. I won't take a month to respond this time.

**Comment by OrangeDrangon** [comment]
They look great. I will get them rasterized for use. Thanks so much. I will try to remember to add an attribution in both the commit and the about window.
