### ISSUE TITLE
macOS Big Sur changes in iconography 

### ISSUE THREAD

**Issue by sallzt** [OrangeDrangon/android-messages-desktop#169]
macOS Big Sur introduces changes in macOS iconography, namely the specification that all icons should be rounded squares. This application should be updated to support this new specification.
I have included a mockup of what a potential Big Sur icon could look like, if maintainer wants I'll adjust according to preferences and upload source files for it. I'm willing to do all the design work to make this happen, I'd like it to match the other icons on my dock e.g. Facebook Messenger.
![android-messages-macosbigsur](https://user-images.githubusercontent.com/18537928/99688352-88693c80-2a3a-11eb-926d-a274e8913409.png)

**Comment by OrangeDrangon** [comment]
Looks good. I will once again look into it when I get time.

**Comment by OrangeDrangon** [comment]
@sallzt I know it has been a real long time but if you want I am confident I should be able to

**Comment by oparada1988** [comment]
Not sure if this belongs here, but it has to do with icons. on a 4k display the tray icon shows like this on MacOS Big Sur

<img width="461" alt="Screen Shot 2021-04-05 at 11 16 41 PM" src="https://user-images.githubusercontent.com/4031078/113654098-1ef26f00-9665-11eb-8811-c8decbd700c2.png">
