### ISSUE TITLE
macOS menu bar icon incorrect resolution/scaling

### ISSUE THREAD

**Issue by sallzt** [OrangeDrangon/android-messages-desktop#170]
next to other menu bar icons, the resolution is clearly incorrect and appears highly pixelated
perhaps you have not included a 2x scale icon for retina display support?
I have attached a screenshot of my menu bar, with the icon on the far left of other correctly scaling menu bar icons 
this bug affects me running macOS Big Sur, presumably this affects other macOS versions as well
<img width="237" alt="Screen Shot 2020-11-19 at 6 53 22 PM" src="https://user-images.githubusercontent.com/18537928/99752071-7fa75380-2a98-11eb-8994-8a5c313bb1aa.png">

**Comment by OrangeDrangon** [comment]
I cannot really fix that as the graphic I have for mac tray is limited in dimension. If someone wants to somehow make a bigger version of the same icon. The file in question is icon_macTemplate.png

**Comment by OrangeDrangon** [comment]
I think I fixed it with waifu2x
