### ISSUE TITLE
Snapcraft Publication

### ISSUE THREAD

**Issue by ceiphr** [OrangeDrangon/android-messages-desktop#174]
**Is your feature request related to a problem? Please describe.**
This project offers snap packages, but is not published on the Snapcraft store.

**Describe the solution you'd like**
Publish the project on the Snapcraft store.

**Additional context**
I've never had to install a `.snap` file before, and every time I do, it fails to install. I think offering the snap through the snap store will reduce confusion and make this project more user friendly to install.

**Comment by OrangeDrangon** [comment]
I will look into in the coming days. Sorry about the delay.

**Comment by OrangeDrangon** [comment]
I disputed the name on snapcraft a few weeks ago decision is still pending.
