### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by nickfilerman** [OrangeDrangon/android-messages-desktop#176]
Similar to that of #158 (I wanted to create a new post, as its a different bug), I am not getting notifications on Pop OS, based off of Ubuntu 20.10

I notice that there is no listing of the application within the notification settings, so I think the issue may stem from there. I have the notifications turned on through the application

The icon in the status bar does change when I get a text, so I know it is getting the update, it just isn't sending the notification to gnome

Other than this issue, this application works perfectly! Keep up the great work!

**Comment by mstras** [comment]
I am having the same issues. None of the notifications are coming through the action center.

**Comment by landalezjr** [comment]
I am having the same issue on MacOS.  Notifications have stopped and it no longer shows up as a notification service in settings.

**Comment by OrangeDrangon** [comment]
I have noticed strange behavior from the notifications. They seem to be working again after some time of not working. The image is still broken but I am looking into ways to make everything more consistent.

**Comment by OrangeDrangon** [comment]
I think it is all resolved now

**Comment by vannaka** [comment]
I can confirm that notifications are working again! Thank you.

**Comment by OrangeDrangon** [comment]
Sorry about the delay, glad everything is working again.
