### ISSUE TITLE
Tray Menu Recent Contacts

### ISSUE THREAD

**Issue by ceiphr** [OrangeDrangon/android-messages-desktop#177]
**Describe the solution you'd like**
The Android Messages app offers "most recent contacts" when you hold down the app's icon. Would it be possible to find the most recently messaged names in the `webview` and add them to the tray menu?

**Comment by OrangeDrangon** [comment]
This should be feasible nice suggestion.

**Comment by vanowm** [comment]
How about this?
![image](https://user-images.githubusercontent.com/511517/107914844-449aac00-6f31-11eb-9c35-8449d20ca7da.png)

**Comment by vanowm** [comment]
How about this?

![image](https://user-images.githubusercontent.com/511517/107918415-9fcf9d00-6f37-11eb-8d35-a46cf63235be.png)

**Comment by vanowm** [comment]
How about this?

![image](https://user-images.githubusercontent.com/511517/107918562-ec1add00-6f37-11eb-8cbe-3f1389342f49.png)

**Comment by OrangeDrangon** [comment]
I would restrict it to names alone. That seems very busy with the pictures and recent text content.

**Comment by ceiphr** [comment]
I really like the pictures and the unread indicators.

**Comment by vanowm** [comment]
I've added options in Settings menu that allow set number of conversations, icon size and show/hide text preview.
