### ISSUE TITLE
Settings Module Rewrite

### ISSUE THREAD

**Issue by OrangeDrangon** [OrangeDrangon/android-messages-desktop#182]
**Is your feature request related to a problem? Please describe.**
Settings are messy and hard to use and modify.

**Describe the solution you'd like**
Custom solution probably using observables. Open to other thoughts. I am not enjoying how the current settings module types everything.

**Comment by vanowm** [comment]
Are you thinking about get rid of `electron-settings` all together or change the way setting get/set?

I was thinking about get rid of all these `SETTING_*` constants and create a single function that would handle get/set for all settings, including handling default values.

**Comment by OrangeDrangon** [comment]
I will be removing electron settings and cleaning it up.

**Comment by vanowm** [comment]
Why does each setting has to be imported separately? Can't we just have one object "settings" and access all it's values whenever/wherever we need?

**Comment by OrangeDrangon** [comment]
There is one single object you can import that has all the settings attached but that should not really matter because any IDE will auto import them for you on use.

**Comment by vanowm** [comment]
I see.
So, why bother export and import individual setting than?

**Comment by OrangeDrangon** [comment]
No real reason and I am open to not doing so. It is convenient but not
really necessary.

**Comment by vanowm** [comment]
In that case, allow me propose this `settings.ts`

```
import { BehaviorSubject } from "rxjs";
import jetpack from "fs-jetpack";
import { SETTINGS_FILE } from "./constants";


function getSetting(key: string): boolean|number|string | undefined {
  return (jetpack.read(SETTINGS_FILE(), "json") || {})[key];
}

interface Settings { [name:string]: BehaviorSubject<any> }

interface DefaultSettings { [name:string]: boolean | number | string }

const settingsExport:Settings = {};

const defaultSettings:DefaultSettings = {
  "trayEnabled": false,
  "notificationSoundEnabled": false,
  "hideNotificationContentEnabled": false,
  "respectSystemDarkModeEnabled": true,
  "startInTrayEnabled": false,
  "autoHideMenuEnabled": false,
  "seenMinimizeToTrayWarning": false,
  "seenResetSettingsWarning": false,
};

if (!jetpack.exists(SETTINGS_FILE())) {
  jetpack.write(SETTINGS_FILE(), defaultSettings);
}

/**
 *
 * initial must be a json serializable type
 *
 * @param key name of setting
 * @param initial initial value if unset
 */
function createSetting<T>(key: string, initial: T): BehaviorSubject<T> {
  const savedVal = getSetting(key);
  const val = savedVal != null ? savedVal : initial;
  return new BehaviorSubject(val) as BehaviorSubject<T>;
}

for(const name in defaultSettings)
{
  settingsExport[name] = createSetting(name, defaultSettings[name]);
  settingsExport[name].subscribe(<T>(val: T) => {
    const data = jetpack.read(SETTINGS_FILE(), "json") || {};
    data[name] = val;
    jetpack.write(SETTINGS_FILE(), data);
  });
}

export const settings = settingsExport;

```

**Comment by OrangeDrangon** [comment]
Explicitly typing the settings object is important to me.  It allows for much better use of typescript allowing each `BehaviorSubject` to be type safe, Your current implementation is much less safe. Though I like the idea of a default setting object, I will see if it works nicely.
