### ISSUE TITLE
4.3.0 on Big Sur - "You do not have permission to open the application"

### ISSUE THREAD

**Issue by manishie** [OrangeDrangon/android-messages-desktop#190]
**Describe the bug**
When installing 4.3.0 in Bug Sur, I get the message "You do not have permission to open the application".  Right clicking on the app in finder and selecting Open does not allow me to bypass (this method worked when I downgraded to 4.2.0)

**Desktop (please complete the following information):**
 - OS: Big Sur
 - Version 4.3.0

**Comment by OrangeDrangon** [comment]
This issue is probably going to go nowhere unless someone with a mac can help. I have the same problem in #164 

Sorry

**Comment by manishie** [comment]
Actually, problem solved!  When I downloaded from the mac zip file, expanded it and ran that version, I got the error above.  When I downloaded from the .dmg file it worked fine!  So just kill the mac zip download you have.  Also as most mac users would know, since this app isn't signed you need to right click and use the open menu the first time, or you can allow the app to run the first time from the Security and Privacy preferences.

**Comment by OrangeDrangon** [comment]
Awesome thanks.
