### ISSUE TITLE
Can't drag Android Messages by title bar in macOs Big Sur

### ISSUE THREAD

**Issue by bpappin** [OrangeDrangon/android-messages-desktop#199]
When Android Messages is in the foreground, you can't drag it around the screen by click-hold the title bar.

**To Reproduce**
1. Install macOs Big Sur
2. Install and hook up to your messages
2. bring to foreground
3. Click on the title bar and attempt to drag the window.
4. Bring another window in front of the messages window, then click the messages window title bar, and you are now able to drag.

**Expected behavior**
Window should be draggable while in the foreground

**Screenshots**

I've got a little screen recording of the problem if needed, but it wont upload to the ticket.

**Comment by bpappin** [comment]
This looks like a duplicate of #164

**Comment by OrangeDrangon** [comment]
Duplicate
