### ISSUE TITLE
Updater uninstalled old version but didn't install new version

### ISSUE THREAD

**Issue by LeGiangAnh** [OrangeDrangon/android-messages-desktop#207]
**Describe the bug**
There was an update notice telling me that the app will update after exit. But the updater only uninstalled the old version but didn't install the new version

**To Reproduce**
1. Notice the update notification
2. Exit the app
3. Wait for some minute
4. Notice that the app was deleted but there isn't a new version installed

**Expected behavior**
The new version should be installed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by OrangeDrangon** [comment]
Time to learn about electron and the auto updater. Everything related to that was from the original project.

I will do some reading and get back to you.
