### ISSUE TITLE
Portable version is not portable

### ISSUE THREAD

**Issue by vanowm** [OrangeDrangon/android-messages-desktop#216]
A portable program supposed to keep all it's settings and any dynamic content within the same directory it's launched from. This way if it's launched from a portable device (flash drive) after application quit and drive removed, there wouldn't be any traces of the application left on the computer.

Current implementation of "portable" version stores settings in %appdata%/android-messages-desktop

**Comment by OrangeDrangon** [comment]
I do not know how to detect if the application is in portable mode and change where the settings are saved. At the moment we are using a npm package for settings so I am not even sure it is possible. I am planning on rewriting the settings module though as it is quite clunky at times.

**Comment by OrangeDrangon** [comment]
Now that we use a custom settings module I would be happy to fix the problem with settings storage if you could point me to an article or documentation on how to detect portable mode.

Otherwise I am going to close this and mark it won't fix in a few days.
