### ISSUE TITLE
Notifications are not fired after launch

### ISSUE THREAD

**Issue by vanowm** [OrangeDrangon/android-messages-desktop#229]
After launch with `Start in Tray` setting disabled, no new message notifications are fired until any conversation was opened.

Windows 10 x64

**Comment by vanowm** [comment]
The patch created even worse new issue: if AM is not linked to a phone (displays QR code), and tray icon disabled - no window opened at all, making AM totally unusable.

**Comment by OrangeDrangon** [comment]
> The patch added even worse new issue: if AM is not linked to a phone (displays QR code), and tray icon disabled - no window opened at all, making AM totally unusable.

please raise issues like this in their own new issue in the future so I actually see them.
