### ISSUE TITLE
last update will not open and run on mac with big sur

### ISSUE THREAD

**Issue by plastik46** [OrangeDrangon/android-messages-desktop#253]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rdivanji** [comment]
Same here on Windows 10 20H2. After the update, I try to open the program and it just doesn't do anything.

**Comment by OrangeDrangon** [comment]
Oh no....

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by OrangeDrangon** [comment]
A rollback of the electron version is build right now that appeared to fix it on my windows vm.

**Comment by rdivanji** [comment]
Yup fixed for me! Had to 'reinstall' using the non-portable exe.

**Comment by OrangeDrangon** [comment]
Sorry about that everyone
