### ISSUE TITLE
macOS doesn't check for updates

### ISSUE THREAD

**Issue by lastbreak** [OrangeDrangon/android-messages-desktop#257]
**Describe the bug**
The 'Check for updates' in menu does not work and no dialog box to tell if there are updates or not.

**To Reproduce**
1. Go to 'Menu AndroidMessages'
2. Click on 'Check for updates'
3. Wait for a few seconds
4. Nothing appears on screen

**Expected behavior**
It should have a message saying if there are new updates or not, and if there are a redirect link for the website download page of the new version.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.7

**Comment by OrangeDrangon** [comment]
The way checking for updates works is it is all in the background and it
updates on app restart.

**Comment by lastbreak** [comment]
Ok, thanks for the information but it will be interest to add this dialog box feature.
