### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by mstras** [OrangeDrangon/android-messages-desktop#258]
![2021-01-26 18_06_12-Window](https://user-images.githubusercontent.com/63074762/105918103-60312780-6001-11eb-92ef-0839949c5ac5.png)

I use Drak reader and it is doing something funky to the app when my system shifts to dark mode on windows. If I toggle Dark Mode it looks fine. This only happened in the last week. 

Thanks,

**Comment by vanowm** [comment]
It seems google changed the way dark theme is being applied.
https://github.com/OrangeDrangon/android-messages-desktop/blob/5cf931f11d0e0f6234e85c37701bef7352cc22f7/src/bridge.ts#L66 is no longer working.
Google now adds dark theme stylesheet only when user enabled dark theme in 3-dot menu and removes it when it's disabled. So at this point AMD will have to supply it's own dark theme or somehow force trigger the setting in 3-dot menu

P.S.
_Dark Reader extension for a browser? If so, it has nothing to do with this messenger..._

**Comment by mstras** [comment]
I guess everything has to be difficult. Must have been changed in chrome 88.

**Comment by vanowm** [comment]
Just enable the dark theme in 3-dot menu

**Comment by mstras** [comment]
That would have to be enabled at all times right? It can't toggle with
system?

**Comment by vanowm** [comment]
Correct. At this moment system dark mode toggle is broken.

I've tried two work around methods:
A) use _custom_ style injected by the app (just a copy of google's dark theme), works pretty much exactly as before
B) switch theme via 3dot menu

Both methods have issues:
A) 
1. generic avatars (avatars with letter) don't change font color.
2. The style have to be manually updated when google changes theirs.

B)
1. theme setting saved globally in the account. So it will affect google messages for web in browser as well.

At the moment method A seems to work the best

**Comment by vanowm** [comment]
Found another way for A) variant, which no longer uses _custom_ style, it removed issue 2.
But there are still 2 side effects:

1. generic avatars (avatars with letter) don't change font color.
2. on startup splashscreen is always dark

**Comment by OrangeDrangon** [comment]
Dark theme settings are synced with the cloud because it is a setting that google manages. I removed any control the electron app tries to exert over the theme due to google being as obtuse as possible with their implementation.

 I may try to have the app control the theme again in the future but using google's method is almost guaranteed to work and has the convenience of syncing between instances.

**Comment by LordMethenor** [comment]
Is it possible to leave an option for the style change in settings? I get you don't want to have to constantly be fixing Google's...obtuseness, but maybe you could provide an option in the menu bar to toggle a basic invert effect (like dark reader). It might be a half measure, but it's still better than what the PWA offers.

I have my system set to switch themes at sunset/sunrise, and it would be nice if it would fit in, even imperfectly. as it stands, only the menu bar changes color, creating an odd sandwich between the window bar and website.
