### ISSUE TITLE
Infinite Loading Animation on Startup

### ISSUE THREAD

**Issue by vanowm** [OrangeDrangon/android-messages-desktop#288]
Is it just me, or as of yesterday this version of AMD is no longer working?
It shows QR code, but after login, it get stuck at loading conversation list.
![image](https://user-images.githubusercontent.com/511517/107361445-631e2480-6aa5-11eb-8c54-dab9f8b970ab.png)

I've tried roll back source and compiled versions, none work for me.

The original 3.1.0 is still working though.

Windows 10

**Comment by napes22** [comment]
Same issue, no longer working with a loading animation.

**Comment by innesst** [comment]
Same - 
Was getting texts today, but it got stuck on loading when I refreshed . If I unpair, it will accept the QR code for a new pairing and go into dark mode, so it is communicating with the server.
Messages in a chrome tab works without issue.

**Comment by innesst** [comment]
4.2.0 works

**Comment by agentlotek** [comment]
I Can confirm that 4.2.0 works.
I tried the following versions
4.5.1
4.5.0
4.4.0
4.3.1
4.3.0
All of these other releases now hang at the same loading animation after pairing.

**Comment by REMjn832** [comment]
I am experiencing the same issue. Perpetual loading cursor.

**Comment by znoble360** [comment]
It appears that the application, at least to some extent, still successfully pairs to my phone, since the desktop client still gives notification sounds when I receive a text on my phone, but it is still stuck on the loading screen as others have stated above and I cannot see any messages.

**Comment by Drakonas** [comment]
I have the same issue. Is 4.2.0 safe to use?

**Comment by agentlotek** [comment]
> I have the same issue. Is 4.2.0 safe to use?

Should be just fine as there are most likely a lot of people using that version anyway because as far as I know, the app has no automatic update feature. This means that whatever version number you download and install never changes unless you manually uninstall then install the latest version.

**Comment by OrangeDrangon** [comment]
Investigation pending.

**Comment by OrangeDrangon** [comment]
Clicking `start chat` allows you to start/resume conversations.

Clicking a notification will also bring you to a conversation after you have done this.

**Comment by vanowm** [comment]
It seems changes in https://github.com/OrangeDrangon/android-messages-desktop/commit/9cfa73a55dbb285060df038888f10cc7dbc5c96b commit has broken the app..

**Comment by vanowm** [comment]
It seems changes in https://github.com/OrangeDrangon/android-messages-desktop/commit/9cfa73a55dbb285060df038888f10cc7dbc5c96b commit has broken the app.
Specifically:
https://github.com/OrangeDrangon/android-messages-desktop/blob/9cfa73a55dbb285060df038888f10cc7dbc5c96b/src/index.html#L8
Removing `nodeintegration` seems to revive the app.

**Comment by OrangeDrangon** [comment]
Awesome work man. Thanks so much. That saved me a lot of effort debugging.

**Comment by OrangeDrangon** [comment]
Everything should be good everyone.

**Comment by vanowm** [comment]
I wonder, these options: `nodeintegration`, `plugins` , do they only affect loaded from the web javascript, or javascript from app itself too (`app.ts`, `bridge.ts`)?
So far I see no reason having `plugins` there either.

**Comment by OrangeDrangon** [comment]
> > as far as I know, the app has no automatic update feature.
> 
> Actually, there is automatic update. Unfortunately it will install the app without user's consent, especially if one is running "portable" version it will still install it as "normal" version into default path - no bueno, me no like.

I literally have no idea how the auto updater works. It is from the fork and I haven't bothered to look at it because to be honest I do not use an OS where it is relevant.

> P.S.
> I was about to reinstall system trying figure out what did I do to upset AMD...

please never do this. this software is doing nothing that would require a full reinstall

**Comment by REMjn832** [comment]
Thanks very much! Resolved for me now.
