### ISSUE TITLE
How do you unhide the file menu?

### ISSUE THREAD

**Issue by agentlotek** [OrangeDrangon/android-messages-desktop#289]
I cannot find any documentation on the hotkey/shortcut to unhide the file menu.
Please share with me your wisdom.

Thanks in advance,

**Comment by innesst** [comment]
On windows, the standard press of the alt key works.

**Comment by agentlotek** [comment]
> On windows, the standard press of the alt key works.

I bow before your wisdom good sir.
Thank you so much, I was going insane trying to figure it out.

**Comment by OrangeDrangon** [comment]
For future reference it is alt on linux and windows.
