### ISSUE TITLE
Installed on Windows 10 - get a Javascript error

### ISSUE THREAD

**Issue by feerlessleadr** [OrangeDrangon/android-messages-desktop#29]
Hi - I just installed this on Windows 10 Pro, and I'm getting the below error:
![error](https://user-images.githubusercontent.com/288895/84433180-e710cb80-abfb-11ea-8533-9e61983b7874.png)

I've tried both the portable version as well as the installer, both give me the same error. 

After I close the error, Android Messages says that it's running (I can see it in my task Manager), but it isn't in my taskbar or anything like that. 

Thanks

**Comment by OrangeDrangon** [comment]
@feerlessleadr This will be patched in v4.1.0 which I will try to have out by tonight. I inadvertently discovered another windows bug I need to fix before I drop this. If you want to use a build that works there will be a link in PR #30 where you can download an unreleased binary.

**Comment by feerlessleadr** [comment]
Awesome - thanks!
