### ISSUE TITLE
Error when trying to run Android Messages Desktop from source

### ISSUE THREAD

**Issue by cmpickle** [OrangeDrangon/android-messages-desktop#290]
**Describe the bug**
I have forked and cloned the repo then I did a `yarn install` and `yarn start`. Once I started it the program started but only displays the dev tools and not the app itself. There is the following error message in the console.
![image](https://user-images.githubusercontent.com/16341707/107441488-89b67c80-6af2-11eb-9b17-ca6b65876c60.png)

Relevant Info
node v15.6.0
yarn v1.22.10
electron v11.2.1
OS: Arch

**To Reproduce**
1. Clone repo
2. yarn install
3. yarn start

**Expected behavior**
The app starts correctly

**Desktop (please complete the following information):**
 - OS: Arch
 - Version rolling

**Comment by OrangeDrangon** [comment]
Couple of questions:

Does this effect the functionality of the app?
Are you using the latest head as of 27 mins ago?

**Comment by cmpickle** [comment]
The app itself didn't display, only the dev tools. I had latest of about 2 hours ago. I'll try the latest again tonight.

**Comment by cmpickle** [comment]
With the latest I am still getting the error and I don't see the app itself when I run `yarn start` just the dev tools. Is there a separate command that needs to be ran for the app to start or should it start along with the dev tools?

**Comment by vanowm** [comment]
The errors in the console are not related to the issue of no window is showing.
It's due to failed patch for issue #229

Three are 2 new patches available:
#268 - just a patch
#272 - new features including #268 patch.

**Comment by OrangeDrangon** [comment]
https://user-images.githubusercontent.com/25403517/107457607-5ee31d00-6b20-11eb-94a3-c6c14b70bff8.mp4

Works from clean for me.

```
~ ❯ node --version
v15.5.1
~ ❯ yarn --version
1.22.10
~ ❯ electron --version
v11.2.3
```
