### ISSUE TITLE
Merging multiple branches into one is a nightmare

### ISSUE THREAD

**Issue by vanowm** [OrangeDrangon/android-messages-desktop#295]
As suggested I've been creating a new branch for each new feature.
So I decided test them all together by creating a test branch for each and merge them all together...what a nightmare that turned out to be. Each merge would delete modifications in the same file from previous merges...I had to track each single modification manually...

Is there anything better could be done about it?

P.S.
[combined patches](https://github.com/vanowm/android-messages-desktop/tree/combined/master)

**Comment by OrangeDrangon** [comment]
yes.

> Each merge would delete modifications in the same file from previous merges...I had to track each single modification manually...
This is antithetical to the purpose of and use of git. You are clearly doing something wrong. 

What you may ask? I do not know.
