### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ikeeki320** [OrangeDrangon/android-messages-desktop#303]
Is it possible to get the notification banner changed to alert style? I don't see the app in my System Preferences --> Notifications settings.

**Comment by ikeeki320** [comment]
The app just showed up in system preferences and I changed it from banner to alert, but the alert still goes away by itself after a few seconds.

**Comment by vanowm** [comment]
I've been doing research how to make notifications persistent, and so far everything points out that it's limitation of Electron itself...
Perhaps https://github.com/mikaelbr/node-notifie could be adopted.

**Comment by OrangeDrangon** [comment]
The nice part of the Electron API is that it mirrors Browser API closely.

**Comment by OrangeDrangon** [comment]
I have no intention to move from the built in method for creating notifications with electron. If you would like to see a change I would open an issue with the electron people if this is actually an issue with their implementation and not me doing something wrong.

If it is me doing something wrong feel free to point me in the right direction to fixing it or a link to the electron docs addressing the issue.
