### ISSUE TITLE
App won't register in Windows 10 notification settings

### ISSUE THREAD

**Issue by Joecascio2000** [OrangeDrangon/android-messages-desktop#330]
**Describe the bug**
I installed the windows version and the app doesn't show in the windows 10 notification settings menu (Settings > System > Notifications and actions). Since it isn't registering in that menu, I am also not getting toast notifications. However, my other programs are working such as Pushbullet for Chrome using native windows 10 notifications.

**To Reproduce**
Install, that's it

**Expected behavior**
Android Messages 5.0.0 should show in the notification settings where I can configure those options

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version 19042.868

**Additional context**
I tried running SFC scan and DISM. Uninstalling and reinstalling.
If I install the chrisknepper 3.1.0 version, it does show in the Notification and actions menu.

**Comment by innesst** [comment]
It seems you can configure notifications through the 3 dot menu settings of the application itself, including if they show, previews and sound.

**Comment by l33tlinuxh4x0r** [comment]
I have also noticed that if you disable notifications in windows that you cannot reenable them as it doesn't show in notifications/settings.

**Comment by Joecascio2000** [comment]
> I have also noticed that if you disable notifications in windows that you cannot reenable them as it doesn't show in notifications/settings.

This is the issue. I think other apps do something to re-register themselves in Windows 10 notification settings. This one does not.

**Comment by Joecascio2000** [comment]
![2021-05-03 19_01_50-Window](https://user-images.githubusercontent.com/2560796/116953462-285dff80-ac42-11eb-9fe3-c5a2cb471d58.png)

Event viewer shows this.

**Comment by innesst** [comment]
Do the notifications not work for you when you use enable them under the 3 dot menu? They do for me.

**Comment by Joecascio2000** [comment]
Can someone go into regedit and send me a screeny of: Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings

I want to see what happens if I add the entry myself.

> Do the notifications not work for you when you use enable them under the 3 dot menu? They do for me.

Nope, that three dot menu doesn't work unless the app is registered in Windows 10 notification settings.

**Comment by innesst** [comment]
Android Messages is not in my Windows 10 notification settings, but the notifications work fine.

I have this entry:
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\pw.kmr.android-messages-desktop
     (Default) = blank
     LastNotificationAddedTime = 1d7408fef533000

**Comment by Joecascio2000** [comment]
> Android Messages is not in my Windows 10 notification settings, but the notifications work fine.
> 
> I have this entry:
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\pw.kmr.android-messages-desktop
> (Default) = blank
> LastNotificationAddedTime = 1d7408fef533000

Interesting. I didn't have an entry there. I created it and it still didn't work.

What about here: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications

Either in Applications or Backup?

**Comment by innesst** [comment]
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications\Backup\pw.kmr.android-messages-desktop
  (Default) = blank
  appType = app:desktop
  Setting = s:banner,s:toast,s:audio,c:toast,c:ringing
  wnsId = NonImmersivePackage

**Comment by Joecascio2000** [comment]
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications\Backup\pw.kmr.android-messages-desktop
> (Default) = blank
> appType = app:desktop
> Setting = s:banner,s:toast,s:audio,c:toast,c:ringing
> wnsId = NonImmersivePackage

Thanks. I also didn't have the registry entry. I have sound but no toast. :( 
That's also all I can think of to fix it. 

I just don't have this issue with the knepper version. But this version is better and more updated.

**Comment by Ratismal** [comment]
Just wanted to share my experiences on Windows 11. No notification sounds or toasts at all, but when I apply both registry changes as specified above, I get both sound and toasts. It's a bit annoying that it has to be manually applied, but manageable I suppose.

This issue has been inactive since May 3rd. Has there been any investigation done since then? If not, I can see if I can tackle the problem myself.

**Comment by OrangeDrangon** [comment]
I forgot about this issue. I have no idea what is causing it but I can look into it.

**Comment by OrangeDrangon** [comment]
I have tried installing custom versions with different setAppUserModelId matching the installed name. Nothing makes it show in the notification settings. I am kind of stumped. Anyone willing to do research, dig up obscure issues on the internet, or solve the problem are appreciated. My google fu is failing me at this particular moment where most of my searches are clashing with irrelevant information.

**Comment by RogerinNYC** [comment]
Not a coder, but interested in this discussion. Running Windows 10. I do get system sounds and notifications when a message is received by 5.3.1, but they disappear quickly and never show in the notification center. But the app itself -- unlike the Knepper app -- does NOT show up in the Windows 10 Notification Settings. This is important because if it's there, I can use accessibility settings to have the notification stay up longer (e.g., for as long as a minute).

Regardless, thanks for your coding efforts and for keeping this up to date!

**Comment by OrangeDrangon** [comment]
My most recent build in #368 should resolve this. Please download and test it.

**Comment by Joecascio2000** [comment]
> My most recent build in #368 should resolve this. Please download and test it.

I can confirm it's fixed on my end although you do have to receive at least one notification after updating for it to register. I just texted myself and then checked and it was there with all the options. 👍
