### ISSUE TITLE
"Android Messages is ready" notification

### ISSUE THREAD

**Issue by dawaltconley** [OrangeDrangon/android-messages-desktop#335]
**Describe the bug**
I get the "Android Messages is ready" notification every time I get a new message. I thought I was getting this instead of the normal notifications (nothing showing the new message content) but I seem to be getting both, but the "is ready" notification persists while the rest go away.

**Expected behavior**
Just the notification with the contact name and message content (I assume the "is ready" notif is for once the app is linked?).

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Version 5.1.1

**Comment by OrangeDrangon** [comment]
Unable to replicate with 5.1.1 deb install on fresh install of Pop!_OS 20.10

Any more details or steps to replicate would be great.

**Comment by dawaltconley** [comment]
I did log in & sync messages to Firefox before installing the app (did not turn on notifications in Firefox). Have since tried reinstalling the app, unsyncing all devices and resyncing to only the app, but it's persisting. I can't think of anything else I would try to reproduce at the moment...will poke around a little more when I have time.

**Comment by OrangeDrangon** [comment]
Let me know if you find anything!

**Comment by dawaltconley** [comment]
Okay after trying a few different things I'm convinced this is not specific to this app, has something to do with my distro or other settings. I installed an [extension](https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/) to remove the "window is ready" notifs, which took care of that, but the new message notifications are still not persisting, as if getting dismissed as soon as they show up.

However, this also seems to happen when running messages.google.com in Firefox, both in my default profile and in a dedicated app-like profile I was trying. Not sure why but definitely seems not to be specific to this app.
