### ISSUE TITLE
App name is a string

### ISSUE THREAD

**Issue by LeGiangAnh** [OrangeDrangon/android-messages-desktop#337]
**Describe the bug**
In the notification pop-up, the app name is a string instead of "Android Message"

**Expected behavior**
Name: Android Message.

**Screenshots**
![image](https://user-images.githubusercontent.com/5027251/126428592-511ed046-4650-4f08-966f-86deb01e3763.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 5.1.1

**Comment by OrangeDrangon** [comment]
predecessor to #354
