### ISSUE TITLE
android-messages-desktop stopped working

### ISSUE THREAD

**Issue by robson-66** [OrangeDrangon/android-messages-desktop#340]
Today the application stopped working, after launching in the terminal there is an error of this content 
`Error: ENOENT, dev-app-update.yml not found in /usr/lib/android-messages-desktop/resources/app.asar`

However, when I reset the configuration I get this message

![ScreenShot](https://i.postimg.cc/XJBN2jDN/screen.png)

**Comment by OrangeDrangon** [comment]
Can you try reinstalling and let me know what distro/de you are on and how the app was installed?

**Comment by Johnex** [comment]
I'm having an issue in Windows 11 as well. The program loads but the web part of the app does not. It is just a completely white window with the menu bar at the top. Removing the appdata folder and reinstalling does nothing, same issue. I get the same warning as OP when removing the appdata folder.

**Comment by albertshin** [comment]
I got a notification that there is a "new version available, refresh" and clicked it and the app has stopped working after this. I just get a white screen.

I have re-installed using the latest release and same issue.

MacOS.

**Comment by OrangeDrangon** [comment]
I think there are multiple issues here. I will look into it and see what I find.

**Comment by OrangeDrangon** [comment]
# Adressing the initial issues
> Today the application stopped working, after launching in the terminal there is an error of this content `Error: ENOENT, dev-app-update.yml not found in /usr/lib/android-messages-desktop/resources/app.asar`

This is not an error that is breaking the application and unrelated to the not loading.

> However, when I reset the configuration I get this message
> 
> ![ScreenShot](https://camo.githubusercontent.com/e8613e46f9e4cb7474ec031d48c0789cdfe8fdd10f4727e50fbbd494fc2cab05/68747470733a2f2f692e706f7374696d672e63632f584a424e326a444e2f73637265656e2e706e67)

This is expected behavior when reseting the configuration from when I migrated the settings manager.

# Followup Reporting

> I'm having an issue in Windows 11 as well. The program loads but the web part of the app does not. It is just a completely white window with the menu bar at the top. Removing the appdata folder and reinstalling does nothing, same issue. I get the same warning as OP when removing the appdata folder.

> I got a notification that there is a "new version available, refresh" and clicked it and the app has stopped working after this. I just get a white screen.
> 
> I have re-installed using the latest release and same issue.
> 
> Details: macOS Big Sur

This is reproduceable. Interestingly the app is running behind the scenes as it is actively fetching new pairing qr codes in an unpaird instance. Unfourtanetly it is not drawing anything.

**Comment by OrangeDrangon** [comment]
Loading [https://messages.google.com/web/](https://messages.google.com/web/) works fine. This narrows the issue down significantly I think.

**Comment by OrangeDrangon** [comment]
Ok research complete and google changed their headers to only allow iframe loading of the website to SAMEORIGIN. This means use of the `<webview>` tag is no longer possible. I am open to suggestions one potential avenue is loading the website directly and either serving as a dumber wrapper meaning you might as well use the PWA. Another is doing what was said before but also attempting to keep injecting javascript in a new way.

**Comment by Johnex** [comment]
@OrangeDrangon Thanks so much for the fixes Kyle 🎉🥳
