### ISSUE TITLE
Spell check right click not working in 5.2.0

### ISSUE THREAD

**Issue by smikwily** [OrangeDrangon/android-messages-desktop#342]
**Describe the bug**
Spell check right click not working in 5.2.0

**To Reproduce**
I only have one computer to test on, but I'm getting a red line under misspelled words, but right clicking does nothing.

**Expected behavior**
Right click should bring up the Spell Check/Change interface allowing you to select corrected spellings or add a word to the dictionary or possibly a fuller interface (even though it was fairly recent, I honestly can't remember how it works/worked.

I tried to roll back to 5.1.1, but it is fully broken, so can't use that for reference.

It does work in the web based interface if that helps. I tested that in Chrome Version 95.0.4638.69 (64 bit) and confirmed it worked.

All my current computers are running Windows 11, so I can't test on Windows 10, etc.

**Screenshots**
Messages Desktop:
![image](https://user-images.githubusercontent.com/5279581/142239366-d8cdf09d-4373-4d86-b395-c377dac27637.png)

Chrome Browser (yes, I have a lot of crap installed - that is how I roll...):
![image](https://user-images.githubusercontent.com/5279581/142241339-c8179664-45f7-4630-b9a8-7fa99dcc3042.png)
(edited pic to show more options for the interface in Chrome)

**Desktop (please complete the following information):**
 - Windows 11
 - 21H2 (22000.318)

**Additional context**
I've tried launching and installing with Admin rights, but no change. I have not had a chance to reboot to see if that factors in or not.

**Comment by OrangeDrangon** [comment]
Reproduced in Windows. Seems to still work in linux. I will look into it.

**Comment by OrangeDrangon** [comment]
If you want you can try installing the version from the pull request.

[https://github.com/OrangeDrangon/android-messages-desktop/actions/runs/1474348283](https://github.com/OrangeDrangon/android-messages-desktop/actions/runs/1474348283)

**Comment by smikwily** [comment]
Confirmed working in the pull request:

![image](https://user-images.githubusercontent.com/5279581/142435992-08f5c0a1-fb07-4f8d-8708-2609a0408ac4.png)

Very much appreciated!
