### ISSUE TITLE
Windows - Clicking on Notification Doesn't Open App / No Notification Dot 5.2.0

### ISSUE THREAD

**Issue by innesst** [OrangeDrangon/android-messages-desktop#345]
**Describe the bug**
When clicking on the pop up notification, nothing happens. Previously (version 5.0), clicking on the notification would open the application.

A notification dot doesn't appear over the icon in the tray when an unread text message has been received.

**To Reproduce**
1. Receive a text message. Windows will produce a pop up notification
2. No notification dot appears on the icon in the tray
3. Click on the notification
4. Nothing happens

**Expected behavior**
A dot will appear on the icon when there is a new unread message.
Clicking on the notification will open the application.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 21H1

**Additional context**
Both items worked in version 5.0.0 - I never upgraded to version 5.1.1

**Comment by OrangeDrangon** [comment]
I'll look into this later. I believe I already reproduced this doing other testing.
