### ISSUE TITLE
Windows - Clicking link opens page within Android Messages app, not default browser

### ISSUE THREAD

**Issue by bigzdog** [OrangeDrangon/android-messages-desktop#346]
**Describe the bug**
Click a link in 5.2.0 and it will open in Android Messages app where previously it would open in default web browser

**To Reproduce**
1. Click link in message
2. Observe page is opened in Android messages instead of default web browser

**Expected behavior**
Clicking links should open page in default web browser

**Screenshots**
![image](https://user-images.githubusercontent.com/14913934/142474389-a67619ba-d43d-47a3-86f6-3a0dbb4f0bde.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Comment by OrangeDrangon** [comment]
Already fixed
