### ISSUE TITLE
Viewing message with reaction

### ISSUE THREAD

**Issue by ikeeki320** [OrangeDrangon/android-messages-desktop#348]
**Describe the bug**
I will receive a notification that a message has been reacted to, but when I view it on AndroidMessages it does not get marked as read/seen on my phone

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Version 5.2.1
 - Samsung Galaxy S10+ Verizon, Android 11

**Comment by OrangeDrangon** [comment]
This app is just a wrapper to the website with some extra features. I am pretty sure that is Google's fault. I am open to being corrected though.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ikeeki320 ***@***.***>
Sent: Thursday, November 18, 2021 4:05:26 PM
To: OrangeDrangon/android-messages-desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OrangeDrangon/android-messages-desktop] Viewing message with reaction (Issue #348)


Describe the bug
I will receive a notification that a message has been reacted to, but when I view it on AndroidMessages it does not get marked as read/seen on my phone

Desktop (please complete the following information):

  *   OS: macOS 11.6
  *   Version 5.2.1
  *   Samsung Galaxy S10+ Verizon, Android 11

**Comment by ikeeki320** [comment]
Tested it in Chrome and it is a Google issue
