### ISSUE TITLE
bridge.ts preloaded twice?

### ISSUE THREAD

**Issue by vanowm** [OrangeDrangon/android-messages-desktop#353]
I there a reason why bridge.js preloaded in `webpack.config.ts` and in `background.ts`? It seems removing it from `webpack.config.ts` still works.

**Comment by OrangeDrangon** [comment]
One is the actual usage in the app the other is the instructions for how to transpile the file to javascript.

**Comment by vanowm** [comment]
Oh, I see. and the reason it's _working_ because it's using previously converted `bridge.js` saved in `app`.
