### ISSUE TITLE
Display app name instead of id in notification toast on Windows

### ISSUE THREAD

**Issue by vanowm** [OrangeDrangon/android-messages-desktop#354]
Windows 10 no longer require set `appId` for notifications, we can set actual title instead:
`app.setAppUserModelId("Android Messages");`
https://github.com/OrangeDrangon/android-messages-desktop/blob/3bb94a30b53a7b98f7f7daa4e33d2961aaec6c95/src/background.ts#L71

**Comment by OrangeDrangon** [comment]
According to this it is not required but has a performance benefit for setting it.

https://docs.microsoft.com/en-us/windows/win32/shell/appids?redirectedfrom=MSDN

I am sure there is a more correct place to set the name of the application for the os. That is specifically meant to be a unique application id from my understanding.

**Comment by OrangeDrangon** [comment]
https://www.electronjs.org/docs/latest/api/app#appname This may outline how to do that.

**Comment by vanowm** [comment]
My point was whatever is set by that function will be displayed as title of the notification toast, which currently is `pw.kmr.android-messages-desktop`:
![image](https://user-images.githubusercontent.com/511517/145691263-87bc1b68-6257-4633-96a1-2d689c17774a.png)

So if that line omitted, it displays `electron.app.Electron`:
![image](https://user-images.githubusercontent.com/511517/145691065-4562eeec-44a5-4d88-9603-f29275a46927.png)

Or with `app.setAppUserModelId("Android Messages");` it displays:
![image](https://user-images.githubusercontent.com/511517/145691128-ab1715b4-717a-4563-8e2e-515f88d300ff.png)

I don't know how critical it is to follow "proper" format, but at least on Windows 10 21H2 it's not critical.

**Comment by OrangeDrangon** [comment]
I understand your point. I am saying that I am pretty sure that is not the intended way to associate a plain text name to a given application.

This comment outlines what I believe to be the intended way to get a plain text name. Though I may be wrong.

https://github.com/electron/electron/issues/5313#issuecomment-219960855

**Comment by innesst** [comment]
I wonder if this has something to do with the issue people have brought up that this application does not show up in the Windows 10 Notifications Setting. The notifications come through  and I can adjust using Google's options, but there is no way to adjust them using the built in Windows settings (e.g. Number of notifications visible in action center, etc.). 

I have Android Messages in my start menu like is mentioned in electron comment 5313, but the notification is still named pw.kmr.android-messages-desktop. Perhaps Windows only checks to adjust the notification banner if the application is properly showing up in the notification area of Windows settings.

**Comment by innesst** [comment]
This may have useful information / links
https://stackoverflow.com/questions/63933737/electron-app-not-showing-in-notification-settings

#330

**Comment by OrangeDrangon** [comment]
please download the binary the github action produces and let me know if this works.

**Comment by innesst** [comment]
It didn't work - but I have somethings I will try and report back.
I was able to get the name on the notification to change.... I'll putz around and let you know.

**Comment by OrangeDrangon** [comment]
This is fixed in #368. Please download and test.
