### ISSUE TITLE
App won't load

### ISSUE THREAD

**Issue by shareefalis** [OrangeDrangon/android-messages-desktop#356]
**Describe the bug**
open app, Electron is loaded, menu bar is loaded,but actual electron webview window is not loading thus can't use it

**Desktop (please complete the following information):**
 -  macOS 12.1

**Comment by OrangeDrangon** [comment]
Is this consistent across launches or only immediately after install/update?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Shareef Ali ***@***.***>
Sent: Tuesday, December 28, 2021 6:09:37 PM
To: OrangeDrangon/android-messages-desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OrangeDrangon/android-messages-desktop] App won't load (Issue #356)


Describe the bug
open app, Electron is loaded, menu bar is loaded,but actual electron webview window is not loading thus can't use it

Desktop (please complete the following information):

  *   macOS 12.1

**Comment by shareefalis** [comment]
Every time it launches.

**Comment by shareefalis** [comment]
I ran a build and debugged it, it is missing this function on mac.  Dock event handler for activation is missing..

```if (IS_MAC) {
  app.on("activate", () => {
  if (mainWindow) {
      mainWindow.show();
    }
  });
}```

**Comment by OrangeDrangon** [comment]
Thanks for debugging it I will get this fixed ASAP.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OrangeDrangon** [comment]
@shareefalis in a few mins there should be a build on the pull request github action for you to give a go. let me know how if it works.

**Comment by shareefalis** [comment]
I have a better patch set which add macOS dock badge support  and adds the activate function..  clearing the badge depends on the activate function.. doing a pull request
