### ISSUE TITLE
Pictures don't load on 5.3.1

### ISSUE THREAD

**Issue by ikeeki320** [OrangeDrangon/android-messages-desktop#361]
**Describe the bug**
Pictures just have the white spinning display and never actually load

**Screenshots**
Attached
![Screen Shot 2021-12-29 at 12 47 50 PM](https://user-images.githubusercontent.com/19860538/147694032-f72dfb2e-37ec-4733-8b21-65ac5d3c81e4.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.6

**Additional context**

**Comment by OrangeDrangon** [comment]
I cannot reproduce this on linux.

**Comment by ikeeki320** [comment]
It's only happening with new pictures received after updating this morning
to 5.3.1 and some pictures previous to the update. I also checked it on up
to date Mac versions of Chrome and Firefox and it's doing the same thing in
both places. Seems like it might be a Messages issue?

**Comment by OrangeDrangon** [comment]
If you reproduced it in a normal browser I am comfortable saying I didn't break anything. Hope google gets it fixed.
