### ISSUE TITLE
"(1) Messages for Web " is ready

### ISSUE THREAD

**Issue by oparada1988** [OrangeDrangon/android-messages-desktop#363]
"(1) Messages for Web " is ready is displayed in the notifications under Ubuntu 20.04, gnome 3.36

Not sure if this has been brought up before

![Screenshot from 2022-01-20 19-52-45](https://user-images.githubusercontent.com/4031078/150446015-e2b7e8fa-080e-44c4-9c33-8621b4cc14a1.png)

**Comment by OrangeDrangon** [comment]
What makes this a bug?

**Comment by oparada1988** [comment]
I guess not a bug, I wasnt sure if this was a normal behavior hence why I opened the ticket

**Comment by oparada1988** [comment]
I guess it makes it a bug because this notifications pops up before the "actual" notification of the message you receive

**Comment by OrangeDrangon** [comment]
Does it happen a lot?

**Comment by oparada1988** [comment]
Every time I get a message actually. I wil try to get a screen recording for you next time my GF is with me so I can capture it in a control environment

**Comment by OrangeDrangon** [comment]
Are you running multiple instances of the program across computers?

**Comment by oparada1988** [comment]
Yes, but for example im on my laptop RN and my main rig is suspended, so technically my main rig should not get anything until I wake it from sleep.

**Comment by OrangeDrangon** [comment]
I am not sure but it is a limitation by google that only one can be active at once. Maybe the two clients are competing for authorized status not really sure.

**Comment by oparada1988** [comment]
Even if one client is as suspended?(main rig vs laptop?)

**Comment by oparada1988** [comment]
Please allow me to capture the screen recording for your review. I can have this within the next 72 hours before this ticket is closed

**Comment by OrangeDrangon** [comment]
There is no rush and this is not a ticket just a collaborative discussion of issues with my broken software.
