### ISSUE TITLE
AndroidMessages 5.3.1.0 Crashes on Win 10 64bit

### ISSUE THREAD

**Issue by gomactrading** [OrangeDrangon/android-messages-desktop#367]
AndroidMessages 5.3.1.0 Crashes on Win 10 64bit.  It starts and disappears in a couple of seconds.  Service also terminates and disappears from Background processes in most cases. In one instance it kept appearing and disappearing and in another instance it actually run as intended.   Version 5.2.1 working fine on same machine with no odd behavior.

**Comment by OrangeDrangon** [comment]
I was unable to reproduce this.
