### ISSUE TITLE
Add a Silent Installation

### ISSUE THREAD

**Issue by dtantono** [OrangeDrangon/android-messages-desktop#369]
Hi,
i want to add this package to winget (https://github.com/microsoft/winget-pkgs/issues/56654#issuecomment-1086762680) and can you add silent installation please?

**Comment by OrangeDrangon** [comment]
`.\AndroidMessages-v5.3.1-win-x64.exe /S` is silent install when ran from an administrator command line. I just tested it and it worked fine. It is built using electron-builder so it supports whatever that supports by default.
