### ISSUE TITLE
Ver 5.3.1 & Ver 5.3.2 crash in WIN 10 64 bit if run as administrator (properties -> compatibility).  No problem in Ver 5.2.1 as administrator or not.

### ISSUE THREAD

**Issue by gomactrading** [OrangeDrangon/android-messages-desktop#371]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by OrangeDrangon** [comment]
I cannot reproduce this. Without more details in the next few days, I will be closing this.
