### ISSUE TITLE
Request to remove the "Messages for Web" title bar

### ISSUE THREAD

**Issue by chigozie18** [OrangeDrangon/android-messages-desktop#372]
**Is your feature request related to a problem? Please describe.**
The title bar is white on the Android Messages app. It doesn't fit in with the black theme if you have it enabled.

**Describe the solution you'd like**
I'd like for the desktop app to redesigned and look similar to the original app: https://github.com/chrisknepper/android-messages-desktop/releases/tag/v3.1.0.

<img width="1351" alt="Screen Shot 2022-04-09 at 10 40 49 AM" src="https://user-images.githubusercontent.com/43191152/162585362-fa8b55b7-c610-4f2b-97ec-f6b44f5b7a28.png">

This is what it current looks like for this forked version: 

<img width="1257" alt="Screen Shot 2022-04-09 at 10 42 16 AM" src="https://user-images.githubusercontent.com/43191152/162585405-30a6d140-11fd-4316-86fe-2db5ca4123f7.png">

I think it'd be better to remove the "Messages for Web" title bar, as it doesn't add any value. Integrating the minimize, maximize and full screen buttons into the same UI like shown in the previous image would look much better.

**Comment by OrangeDrangon** [comment]
I vaguely recall having to add the title bar because people could not move the window on mac. I can open a pull request with a change for you to play with.

**Comment by OrangeDrangon** [comment]
#164
