### ISSUE TITLE
Load time for messages spins 

### ISSUE THREAD

**Issue by CanningDicks** [OrangeDrangon/android-messages-desktop#373]
Loading conversations takes very long from time to time. No rhyme or reason, tried uninstalling and reinstalling, etc. Not internet connection just app. [
<img width="902" alt="Screen Shot 2022-04-11 at 10 09 17 AM" src="https://user-images.githubusercontent.com/42644036/162758184-98fe6e5a-ad84-41c0-8e83-88e82fc0205d.png">
](url)

**Comment by OrangeDrangon** [comment]
This feels like an issue on googles end as this app should not interfere with that but I am open to evidence to the contrary.
