### ISSUE TITLE
Add option to disable flashing of taskbar icon/button and to disable red unread message dot

### ISSUE THREAD

**Issue by JayceTheBased** [OrangeDrangon/android-messages-desktop#380]
I'm a huge fan of this app and am amazed by how fast it is compared to the last similar forked program I was using. So thanks for your hard work on it. That being said, I would love it if you could make a couple small improvements to this. I have ADHD and so try to minimize things that could cause me sustained disruptions in my focus. Currently, the taskbar button flashing whenever a new message comes in and continuing to flash until I click into it is very distracting to me. Also, a much more minor issue is that of the small red dot on the tray icon, denoting that I have unread messages.

I often do not respond to texts quickly because I like to think for a time before texting. So I would truly appreciate options to disable the taskbar button flashing, and ideally also to turn off the tray icon red dot that denotes having unread messages. Discord has an option for the latter to turn off the unread message badge, which I really like.

I know that I can avoid the taskbar flashing issue by simply closing the program to the tray instead of minimizing it to the taskbar, however, I really prefer to have the program open in my taskbar most of the time for easier access.

Thanks in advance for your consideration with my suggestions :)

**Comment by OrangeDrangon** [comment]
Sounds feasible. After finals I can look at getting a new setting for that up and running.

**Comment by OrangeDrangon** [comment]
Never mind this was a 2 min fix there will be a version with this fix in the next hour. Thanks for the feedback hope this helps with the distractions.

**Comment by JayceTheBased** [comment]
You have no idea how much I appreciate it, thanks so much man! This app is officially as good as iMessages now (not that I'd know, Android for life always).

**Comment by JayceTheBased** [comment]
> Never mind this was a 2 min fix there will be a version with this fix in the next hour. Thanks for the feedback hope this helps with the distractions.

You have no idea how much I appreciate that, thanks so much man. Keep killing the game!
