### ISSUE TITLE
Homebrew Package

### ISSUE THREAD

**Issue by anonymousaga** [OrangeDrangon/android-messages-desktop#382]
I prefer to install my apps via homebrew for easier management/listing. Is it possible to get this app as a homebrew package?

**Comment by OrangeDrangon** [comment]
I know nothing like this but I am open to the idea. I assume someone needs to write a homebrew file of some sort and add it to a repo or something.

**Comment by anonymousaga** [comment]
scroll down to the casks section of this guide: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by anonymousaga** [comment]
sorry, I just realized that forks cannot become casks, only original repos. If you would like to set up a tap instead, then here is a file you can publish to a repo called "homebrew-xxxxxx" with a folder called "Casks" inside it, then the rb file inside the folder.

[android-messgaes-orangedragon.rb.zip](https://github.com/OrangeDrangon/android-messages-desktop/files/8599790/android-messgaes-orangedragon.rb.zip)

**Comment by OrangeDrangon** [comment]
`homebrew-android-messages-orangedrangon`?

**Comment by anonymousaga** [comment]
No, you create a repo called homebrew-anything, such as homebrew-apps. Then anyone can tap OrangeDragon/apps in brew. Create a "Casks" folder inside it, and put the rb file inside the casks file.

**Comment by OrangeDrangon** [comment]
i see. ill do that.

**Comment by OrangeDrangon** [comment]
when i update do i just bump the version in that file?

**Comment by OrangeDrangon** [comment]
https://github.com/OrangeDrangon/homebrew-apps

**Comment by anonymousaga** [comment]
Yes, this is all you have to do to bump the version. On another note, i had to create a pull request to correct a typo in the file from “dragon” to “drangon”. I will test the install tomorrow, after you have accepted the pull request. Then, i will close the issue. Thanks for your cooperation and consideration.

**Comment by OrangeDrangon** [comment]
it is merged

**Comment by anonymousaga** [comment]
ok, just tested. One last typo - "messgaes." I tested with the file, and it works now. Just accept the new pull request i sent you, and it should work. Thanks! You can also state this feature in your readme, if you wish.

**Comment by OrangeDrangon** [comment]
Merged
