### ISSUE TITLE
Notifications on Linux get dismissed automatically

### ISSUE THREAD

**Issue by ErikReider** [OrangeDrangon/android-messages-desktop#391]
**Describe the bug**

When receiving a message, a notification pops up as to be expected but the issue here is that they're getting dismissed automatically without any user input. I'm running my `SwayNotificationCenter` notification daemon which sends all notifications to a "control center" with old notifications that have been hidden due to a timeout.

**Expected behavior**

Notifications shouldn't be dismissed by the application but should be handled by the daemon. (This can always be an option in the settings)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Application Version 5.3.4

**Comment by OrangeDrangon** [comment]
I honestly do not really understand what you mean. There is nothing special being "handled" on the applications notifications excepting adding a click event listener.

**Comment by ErikReider** [comment]
Oh sorry. Testing the web version results in the same issue... My bad. Thanks for your help! :)
