### ISSUE TITLE
Tray icon disappears when I launch the app from exe or through link 

### ISSUE THREAD

**Issue by espdav** [OrangeDrangon/android-messages-desktop#392]
Everytime I want to open Android Messages clicking on the exe file or any link to it, the tray icon disappears. I have to uncheck and re-check 'Enable tray icon' to unhide it. Furthermore, the tray icon remains active if I launch the app from there.

1. Open app and check 'Enable tray icon'
2. Close app
3. Re-open app
4. I notice a white flash on the entire window app (behaviour happening only if the option 'Start in tray' is unchecked)
5. The tray icon is missing.
When I close the window again, the app is still running in background with five instances, which is insane.

**Expected behavior**
I expect to close and run the app from exe/link as often as I want and still see the tray icon active, instead of launching the app from tray icon only.

System info:
 - OS: Windows 11 Pro
 - Version 21H2 Build 22000.918

**Comment by OrangeDrangon** [comment]
I can try to reproduce this later. It seems to be platform specific as it is definitely not happening on my linux box.

**Comment by espdav** [comment]
Ok, please let me know what I can do about it when you checked.

**Comment by OrangeDrangon** [comment]
I have reproduced this behavior on windows 10

**Comment by espdav** [comment]
Yeah very strange, maybe it depends from some windows update. Just wondering...

**Comment by OrangeDrangon** [comment]
I think I have fixed this issue. It seems to be some sort of event race between the quit and ready event. I disabled handling the ready event unless it is the first instance.
