### ISSUE TITLE
Conversation Contents Not Showing

### ISSUE THREAD

**Issue by letter-t** [OrangeDrangon/android-messages-desktop#399]
**Describe the bug**
While the newest text for a conversation will show on the left side, the conversation itself shows nothing when opened. This does not happen on the web version. Pictures included below.

**To Reproduce**
I am unsure about how to reproduce this bug for other people. It has been present since I first used this app. It is persistent across restarts, both for computer and phone, and also persists after re-pairing the device.

**Expected behavior**
As shown in the second image, I expect that the app should show messages within conversations.

**Screenshots**
![image](https://user-images.githubusercontent.com/83261720/192939323-f037c09f-e4e6-47fd-bb54-28bab91bed2e.png)
![image](https://user-images.githubusercontent.com/83261720/192939352-f2afde3f-2490-4f39-925f-274b01d8ead4.png)

**Desktop:**
 - OS: Windows 10 Pro
 - Version 21H2

**Additional context**
I'm not sure if this is a real bug, but I could find no documentation on it, so I will report it as such.
My phone is a Samsung Galaxy A51.

Things I have tried:
- messing with the options on the desktop app and on google messages
- changing permissions on phone for google messages and google play services 
- restarting the phone and the PC
- re-pairing the phone to the desktop app

**Comment by letter-t** [comment]
UPDATE: I tried re-downloading the installer, and it fixed the issue. Should probably have tried that before submitting a bug report. I don't believe this to be a bug anymore, so I will close this issue.

**Comment by OrangeDrangon** [comment]
I have no idea what caused it but if you fixed it all is well I guess.
