### ISSUE TITLE
recieving pairs of identical notifications

### ISSUE THREAD

**Issue by benjaminBrownlee** [OrangeDrangon/android-messages-desktop#40]
**Describe the bug**
Pairs of duplicate notifications on dunst for all received messages. Other applications do not exhibit the same behavior.

**To Reproduce**
1. Launch android-messages-desktop.
2. Receive an SMS message.
3. Receive two identical notifications by the dunst notification server.

**Expected behavior**
Only receive a single notification per message.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Version: 5.7.4-arch1-1

**Additional context**
I have verified that only one instance of dunst is running and that other other applications are not exhibiting this behavior.

**Comment by OrangeDrangon** [comment]
I have occasionally noticed this happening but only in very specific instances. Is this consistent or relatively rare? I believe the times that I see this behavior is if I dismiss the notification too quickly.

**Comment by OrangeDrangon** [comment]
Also does one notification have the contact picture and one does not?

**Comment by rdivanji** [comment]
I also have this issue. The first has a profile picture, the second does not. For me, this happens consistently with every message/notification. 

- OS: Manjaro Linux (Arch based)
- Version: 20.0.3 (OS) 5.4.44-1 (Kernel)

**Comment by OrangeDrangon** [comment]
I am not going to lie I am having trouble reproducing this for some reason. I have seen this behavior before but it is not consistent for me. If I provide a link to a build in the coming future would you guys be willing to test it for me?
