### ISSUE TITLE
Cannot stay logged in when using Google Fi mobile provider

### ISSUE THREAD

**Issue by focuspulling** [OrangeDrangon/android-messages-desktop#405]
Simply put, whereas this desktop app would stay logged in with every reboot using any other carrier, as soon as I switched to Google Fi, and proceeded through the Get Started option for that, the app only stays logged in with each startup, then requires authentication again.  Any way around this?

**Comment by OrangeDrangon** [comment]
Someone else that uses Google Fi will have to chime in. I personally can't use or test the fi feature.

Thanks
Kyle

**Comment by nkean** [comment]
Running on macOS Monterey with Google Fi as my provider and not facing this issue. @focuspulling what OS are you seeing the issue with?

**Comment by focuspulling** [comment]
Sorry that I should have thought to update this thread, but eventually upon logging out and back in, it started keeping me logged in between reboots. Tentatively seems resolved, thanks.

**Comment by Drakonas** [comment]
![Screenshot of failed login](https://i.imgur.com/W4hLLyV.png)

This is actually an issue. I can confirm with my Google Fi account on one machine, and my parent's Google Fi account on another machine. Google seems to block the app, stating "your browser or app may be unsecure". Eventually after trying like 5 times, it can let you in, but I'm not sure for how long. It seems the app is being detected somehow.
