### ISSUE TITLE
Window size and position issue when opening app

### ISSUE THREAD

**Issue by kw0n** [OrangeDrangon/android-messages-desktop#409]
![t0fH10V](https://user-images.githubusercontent.com/13937442/203844941-60bed8ce-c6be-4400-b413-bcf5306b2aff.png)

**Describe the bug**
The android messages desktop app always opens in a unusual position. It will open unmaximized but and off center and have a bit of the window carry over to the secondary display. I have tried to resize the window and reopen the application and also reinstall the application but I could not get it to reposition properly when reopening the application.

**To Reproduce**
1. Open android messages desktop (for windows 11)

**Expected behavior**
Is it possible to have it open in a remembered window size/position?

**Screenshots**
attached and also imgur link below

[LINK](https://i.imgur.com/t0fH10V.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 22H2 (Build 22621.819)

**Comment by OrangeDrangon** [comment]
Honestly I expect it to remember its position as there is code in place to do this. I will try to remember to look into this later.
