### ISSUE TITLE
Add emoji react support for messages received from iOS users

### ISSUE THREAD

**Issue by phodamentals** [OrangeDrangon/android-messages-desktop#410]
**Describe the solution you'd like**
Google messages added emoji react support for messages from iOS users. Can we add this feature to this desktop application? 

**Additional context**
https://blog.google/products/messages/10-new-messages-features/

**Comment by OrangeDrangon** [comment]
out of scope for this app and it already works :)

**Comment by phodamentals** [comment]
@OrangeDrangon Oh, where does it work? I'm running Android Messages Desktop 5.4.0 and when I click on a message from an iOS user I cannot emoji react to it like its mobile Android app counterpart. Do I need to enable anything else?
