### ISSUE TITLE
Emoji reactions to non-RCS messages threads and group chats

### ISSUE THREAD

**Issue by tev-tev** [OrangeDrangon/android-messages-desktop#416]
**Is your feature request related to a problem? Please describe.**
Via the messages for desktop app I'm not able to add a baked-in reaction to a message from an iPhone user (or really any non-RCS) user despite Google adding support for that directly in the app itself

**Describe the solution you'd like**
I'd love to have the emoji button appear next to messages just like the built-in one exists for RCS connected conversations to add a reaction like you'd be able to from your phone.

**Describe alternatives you've considered**
Not to sound like an insane person but this seems like quite literally the only possible way this minuscule issue could be solved to make non-RCS conversations behave like RCS conversations within the context of reaction-based functionality

**Additional context**
Not only do I not have any additional context, I don't understand how one possibly could

**Comment by OrangeDrangon** [comment]
this is a limitation on googles end
