### ISSUE TITLE
Stuck showing Sending...

### ISSUE THREAD

**Issue by kevev** [OrangeDrangon/android-messages-desktop#417]
**Describe the bug**

**To Reproduce**
Send a text

**Expected behavior**
Shows as sent

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Phone:**
- Model: Pixel 6a
- OS: Android 11 latest
- Network; T-Mobile US

**Additional context**
I noticed this got a lot worse in the latest version. Not sure what is going on.

**Comment by kevev** [comment]
I noticed that disabling Ublock Origin in Chrome seems to help. Does this app use Chrome?

**Comment by OrangeDrangon** [comment]
i cannot reproduce this on my machine with trivial effort. I will keep my eyes posted over the next few days.



> I noticed that disabling Ublock Origin in Chrome seems to help. Does this app use Chrome?

it does use the chromium browser engine but as far as I know it should not be affected by extensions in the chrome browser

**Comment by kevev** [comment]
Cancel that. Issue still exits.

**Comment by kevev** [comment]
I am on Google Fiber using Pi-Hole. I have disabled Pi-Hole and still issue. I can try with computer on another network also.

**Comment by kevev** [comment]
It must have been a T-Mobile network issue. Seems all good today. Closing this issue.
