### ISSUE TITLE
support the new 'quoted msg' reply style

### ISSUE THREAD

**Issue by hunleyd** [OrangeDrangon/android-messages-desktop#420]
The latest version of the Messages app on Android allows you to long-press an RCS message and choose 'reply' It then quotes the message you're replying to and your reply goes under that. This makes it easy to have multiple simultaneous chat topics with someone and not get confused about what topic their reply is for. I don't see a way to do this in your app and have to resort to picking up my phone, which defeats the purpose of having your app.

**Describe the solution you'd like**

Add a 'reply to msg' in the kebab menu on RCS msgs where it says 'copy text' and 'delete'. Or, maybe if you double-click an RCS message, it could trigger the 'reply to this msg' functionality.

This is what a reply looks like on the phone:
![Screenshot_20230503-144153](https://user-images.githubusercontent.com/2753418/236014386-37aad88a-0b1b-40e1-bbd7-5135c21174b0.png)

**Comment by LarveyOfficial** [comment]
This isn't something this developer can add, the application simply loads https://messages.google.com/web/
So it won't be update unless Google themselves adds it as a feature.
