### ISSUE TITLE
Ability to search for Emoji

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [OrangeDrangon/android-messages-desktop#422]
**Is your feature request related to a problem? Please describe.**
It is possible to search for an emoji on the phone ( within the app, not dependent on the keyboard ) . Example , search for angry face emoji, and get this 

_How it works on the phone_
[![How emoji search works on a phone](https://i.postimg.cc/QdskVRK7/Phone.gif)](https://postimg.cc/2VcBK9wj)

_How it works currently within Android Messages Desktop 5.4.1_
[![How it works currently within Android Messages Desktop 5.4.1](https://i.postimg.cc/V6pGrDXC/Desktop.gif)](https://postimg.cc/phQY3QGW)

**Describe the solution you'd like**
A text search box to search for emojis.

**Describe alternatives you've considered**
Running a short text search in the browser and copying the emoji from the results is currently an alternative. For most users, a few quick alt+tabs aren't that difficult.

**Additional context**
N/A

**Comment by philogit** [comment]
@OrangeDrangon, I noticed in your comment on another issue [here](https://github.com/OrangeDrangon/android-messages-desktop/issues/419#issuecomment-1533290216) that you tend to defer to the web app for implementation when it comes to complex features. Would consider this request to be relatively straightforward to implement?

**Comment by OrangeDrangon** [comment]
Many os have a ui for this. Google for your respective platform
