### ISSUE TITLE
[Feature Request] Hide from Dock when closed, but keep running in background

### ISSUE THREAD

**Issue by VityaSchel** [OrangeDrangon/android-messages-desktop#423]
hi, thanks for fork
I would like to request you to allow MacOS users to close app's window and hide it from dock, but make it run in background.

**Comment by VityaSchel** [comment]
@OrangeDrangon pls merge 🥹

**Comment by VityaSchel** [comment]
Oops forgot to switch git profile to github, I hope this will not be a problem! @hloth is actually my second account

**Comment by OrangeDrangon** [comment]
I will take a look.

Thanks
Kyle

**Comment by bra1ncramp** [comment]
This may have caused this bug: https://github.com/OrangeDrangon/android-messages-desktop/issues/432
