### ISSUE TITLE
"Auto Hide Settings" Makes Setting Disappear Forever

### ISSUE THREAD

**Issue by epicjono** [OrangeDrangon/android-messages-desktop#428]
I chose the "auto-hide settings" option, and now those settings are gone forever. I have no idea how to bring them back. I had selected "start minimized" or however it was worded, and now my app will start in the taskbar every time with no way to change it! Is there a way to bring those settings back?

I know normally there's a file that can be opened with a text editor and settings can be modified there, but other than that I have no clue. I tried uninstalling and reinstalling, I tried installing through Scoop, I tried opening every single file I could and modifying text in Notepad, but nothing worked. The setting I checked seems to be saved somewhere, so every time I download the app again, it automatically starts in the taskbar and has no option to change that. I'm pretty new to all of this, so any help is greatly appreciated!

**Comment by innesst** [comment]
Press alt

**Comment by innesst** [comment]
This isn't the first time this has come up. Perhaps change menu text to:
    Auto Hide Menu Bar (Press "Alt" to Show)

**Comment by epicjono** [comment]
Wow. So simple and somehow I didn't think to press a few keys. Thanks!
