### ISSUE TITLE
Can't install update via Menu

### ISSUE THREAD

**Issue by Matgen84** [OrangeDrangon/android-messages-desktop#431]
**Describe the bug**
I'm using version 5.4.1. This morning, a notification tell me to update. Nothing happen.

**To Reproduce**
1. Go to 'Dock'
2. Click on '.Android Messages'
3. Scroll down to 'Install update'

**Expected behavior**
This morning, a notification tell me to update. Nothing happen despite of clicking 'Install Update'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Monterey 
 - Version 12.7.1

**Additional context**

**Comment by kevev** [comment]
Same thing happened in Win 10. Instead in the app, click File->Install Update.
