### ISSUE TITLE
Choice of browser or browser profile to open links

### ISSUE THREAD

**Issue by jrlebbs** [OrangeDrangon/android-messages-desktop#433]
**Is your feature request related to a problem? Please describe.**
I use 2 browsers on my computer. One for work and the other for personal. The work one (Edge) is set as default. When I click a link, the default behavior opens Edge.

**Describe the solution you'd like**
A choice of browser for opening links. I use Chrome for my personal browsing.

**Describe alternatives you've considered**
Copy/paste of links between browsers.

**Additional context**
Additional choice of which profile in which browser might be awesome, if people use multiple profiles.

**Comment by OrangeDrangon** [comment]
Open to a patch submission I guess

**Comment by singingotter** [comment]
similar however on Ubuntu Forefox is set as default but Android-messages-desktop always opens Chromium. I'de prefer it to open Firefox unless I choose otherwise.
