### ISSUE TITLE
Stuck trying to to authenticate via google account and can not access QR code verification

### ISSUE THREAD

**Issue by kostecky** [OrangeDrangon/android-messages-desktop#436]
**Describe the bug**
I suspect this is a result of google offering a new way to pair devices with their messaging platform. I foolishly try to enable this on phone and now when I try to open the app, it's stuck asking me to authenticate, but it fails because the electron window is potentially not secure.

Regardless of that, I switched it back to QR code authentication, but because of cookies or some other stateful information that's saved, the app is stuck asking and I can't get it back to requesting a QR code scan.

I've tried uninstalling and reinstalling and even deleting cookies for messages.google.com, but it's not affecting it.

**To Reproduce**
1. When your android app requests that you change pairing mode to "account authentication" do so.
2. Your messages.app will now log out and ask to repair
3. Choose the non-QR code option.
4. Enjoy this fine app being bricked =(

**Expected behavior**
There should be some way to reset the authentication mode OR perhaps have it support authenticating via google auth.

**Screenshots**
<img width="963" alt="Screenshot 2023-12-15 at 9 39 12 AM" src="https://github.com/OrangeDrangon/android-messages-desktop/assets/159611/463e1f6e-c25a-48e8-9a29-d2fc65137c4c">

**Desktop (please complete the following information):**
 - OS X 14.2
 - Android-Messages-v5.4.2-mac-universal.zip

**Additional context**
If there is a way to reset whatever is keeping state, that may be best. Thanks!

**Comment by kostecky** [comment]
I've also tried deleting ~/Library/Application\ Support/android-messages-desktop to no avail.

**Comment by smikwily** [comment]
Getting this in Windows 11 as well.

I can't confirm this works 100%, but I was able to sign in using QR code by signing out of all devices using the Android Message app option to do so (Top right initial/profile pic > Device pairing > Unpair all devices).

I also can't confirm at this time, but I believe when you do this, you may be able to sign in a single device using the new method before it fails for all other devices. Unpair all devices using the above, then try to sign in using the new method. I've been able to get one device logged in, but can't get others as of yet.

**Comment by brazenCoding** [comment]
I was able to sign back in by closing the program, enabling VPN, opening the program and it offered me QR sign in. Then I disabled VPN. Was able to do this twice.

**Comment by GTR8000** [comment]
I initially had trouble signing in with the new Google authentication method. I downloaded and reinstalled v5.4.2, and was able to sign in with the new method immediately, no issues whatsoever.

**Comment by smikwily** [comment]
> I initially had trouble signing in with the new Google authentication method. I downloaded and reinstalled v5.4.2, and was able to sign in with the new method immediately, no issues whatsoever.

I was able to do that on my first device, but no other devices after that would work. I could reset everything and the first device would work fine, but any others would fail with the "not secure" error.

**Comment by eisenbruch** [comment]
This app has been rendered useless for me and it seems to be due to this bug :( - any resolution in sight?

**Comment by brazenCoding** [comment]
> This app has been rendered useless for me and it seems to be due to this bug :( - any resolution in sight?

Have you tried the above mentioned suggestions? I haven't had any issues since following that.

**Comment by eisenbruch** [comment]
> > This app has been rendered useless for me and it seems to be due to this bug :( - any resolution in sight?
> 
> Have you tried the above mentioned suggestions? I haven't had any issues since following that.

For some reason after updating to 5.4.2 logging in with email address showed me the same error due to the new login requirements.
But, I tried it again just now and it worked!
Not sure what was different, but I am logged in now.

Thanks @brazenCoding

**Comment by innesst** [comment]
Having the program present a QR vs login screen is based on Google's back end, not this app. However, I also was unable to login via the app. But I then added the @gmail.com to my username and it worked.

**Comment by mcortt** [comment]
Login via the top sign in option and NOT the one in the page. Also, use your full email address. 
![image](https://github.com/OrangeDrangon/android-messages-desktop/assets/9371806/6a54c4aa-fba6-44e1-94a4-cb847404a311)
