### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by buckmelanoma** [OrangeDrangon/android-messages-desktop#437]
.desktop file needs the following arguments to enable Wayland support (currently only X11 is supported):

`--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`

`qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole` output before:
![Screenshot_20231230_141720](https://github.com/OrangeDrangon/android-messages-desktop/assets/43704682/7d40cc91-06d1-41e7-9bd8-cd846adc27b7)

`qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole ` output after:
![Screenshot_20231230_141929](https://github.com/OrangeDrangon/android-messages-desktop/assets/43704682/5b294596-c065-4c9f-b166-2b5da9f75658)

.desktop file:
![Screenshot_20231230_142306](https://github.com/OrangeDrangon/android-messages-desktop/assets/43704682/c3b94d24-694d-4b04-898b-98b9e210cd87)

**Comment by OrangeDrangon** [comment]
I assume this allows wayland to work without breaking X support?

**Comment by buckmelanoma** [comment]
Correct.  The app still works as expected under X.

Ex:
![Screenshot_20240102_094432](https://github.com/OrangeDrangon/android-messages-desktop/assets/43704682/cc219b07-411c-4db7-b234-8096acc8c636)
