### ISSUE TITLE
Client not secure for android messages login

### ISSUE THREAD

**Issue by ThePianoMan2255** [OrangeDrangon/android-messages-desktop#441]
**Describe the bug**
When attempting to sign in (not with a QR Code) it says it is not a supported browser / secure. See attached image. 

**To Reproduce**
1. Open the app 
2. Click on sign in
3. Attempt to sign in

**Expected behavior**
Should allow you to login in a supported secure setting.

**Screenshots**
![image](https://github.com/OrangeDrangon/android-messages-desktop/assets/61894631/e0ab9df7-3168-4bbc-aa14-6c32cfe5561d)

**Desktop (please complete the following information):**
 - OS: PopOS 22.04 LTS
 - Version: Latest Deb Package: 5.4.2

**Comment by mtballday** [comment]
It seems like the latest version of the phone app no longer supports pairing with the QR code (at least, I can't find it now), so this problem makes it impossible to pair.

**Comment by adelphi23** [comment]
I got stuck on this too, but have a complicating factor. 
In my Macbook Pro M1 Ultra (2021) it worked. That is, I did not the the error message shown above by OP.
In my Macbook Air M2 (2022) it did not. That is, I did get the error message and cannot pair my computer.
It might be that between the two installations the phone app was updated, losing its support for QR-based pairing. I cannot recall doing QR pairing, though.

**Comment by sansbyte** [comment]
I get the same message as the original post - the "This browser or app may not be secure".

However, while troubleshooting, I stumbled across a workaround that lets me login. I tried starting the program with the --debug switch try getting more troubleshooting information to share here.

```shell
$ ./AndroidMessages --debug
[61919:0217/185412.944387:ERROR:node_bindings.cc(244)] Error parsing Node.js cli flags 
electron: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
``` 
So I then tried using the --inspect switch, because why not. The program started and let me login. This is the command output, for what's worth.

```shell
$ ./AndroidMessages --inspect
Debugger listening on ws://127.0.0.1:9229/961741b9-d61c-405d-8c49-44300d11d83a
For help, see: https://nodejs.org/en/docs/inspector
APPIMAGE env is not defined, current application is not an AppImage
[74550:0217/191924.083478:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
``` 
After logging in and closing the program, I can open it again without the --inspect switch and I'm still logged in.

**Comment by maelchiotti** [comment]
Same error on windows 11.

**Comment by innesst** [comment]
I also got the message when trying to login, but then I added the @gmail.com to my username and it worked.

**Comment by maelchiotti** [comment]
> I also got the message when trying to login, but then I added the @gmail.com to my username and it worked.

Doesn't work for me.

**Comment by mcortt** [comment]
Login via the top sign in option and NOT the one in the page. Also, use your full email address.
![image](https://github.com/OrangeDrangon/android-messages-desktop/assets/9371806/768ed508-7c4b-4575-8169-6262f7939fa1)

**Comment by maelchiotti** [comment]
> Login via the top sign in option and NOT the one in the page. Also, use your full email address. ![image](https://private-user-images.githubusercontent.com/9371806/313370380-768ed508-7c4b-4575-8169-6262f7939fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTc1MzksIm5iZiI6MTcxMTI5NzIzOSwicGF0aCI6Ii85MzcxODA2LzMxMzM3MDM4MC03NjhlZDUwOC03YzRiLTQ1NzUtODE2OS02MjYyZjc5MzlmYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjRUMTYyMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA2MzQwZjA3Y2FlZmI5NTcxYTc4NDhmNjcwNDRjYjMzMGNiYTA3YzExZTQ5NzBkODZmNmExODNkZTcxNDQzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OcjZmNSKeeeyHIfSVJxsBxfLUQamj1ZwfYnGQzDcFfU)

Still does not work for me

**Comment by adelphi23** [comment]
Does not work on Fedora 40. Tried with the --inspect toggle using the CLI and also clicked on the top sign. All to no avail. It is the app since the web version works.

**Comment by adelphi23** [comment]
After trying a few times, the sequence:
./AndroidMessages --inspect (click on the top button, use full gmail)
close
./AndroidMessages 
worked. No changes in any other parameter. It is somewhat random.

**Comment by caseyredisatwork** [comment]
For me (running an Arch-based Linux distro), --inspect by itself did not work. I needed to use --inspect, then I had to select "Remove Account", click the red (-) icon next to my account, say "Yes, remove" and then re-enter my credentials. After that, I closed the app and re-ran without --inspect and it still worked.

I thought maybe removing the account itself was what worked so I tried that after things were working from the above but removing didn't resolve the issue without first running --inspect. YMMV, I didn't want to mess around with it much more after getting it to work twice the original --inspect way

**Comment by drislands** [comment]
https://github.com/drislands/android-messages-desktop/tree/bugfix/441

I've attempted a fix. It's working consistently for me now, but I'd like to see if it works for other people before I open a PR.

If there's anyone experiencing this issue, can you clone my project from the link above and see if it works for you?

**Comment by Vilacard** [comment]
I haven't used github much so I'm not really sure what you mean by cloning your project. I thought I could maybe just download your code as a .zip then replace something in my Android Messages install folder with the most recently changed files you did, but there doesn't seem to be a background.ts in my install folder.

**Comment by maelchiotti** [comment]
@Vilacard you cannot juste replace the files, they need to be compiled first. I do know how to use GitHub but I don't have the time right now to setup the environment, would it be easy for you @drislands to build a Windows executable?

**Comment by drislands** [comment]
@maelchiotti I'll see if I can package this up. I haven't done this for a JS project before so it may take some doing.

**Comment by drislands** [comment]
Turns out that's not hard to do. 

@maelchiotti @Vilacard try the EXE attached to this release. I don't have a Windows machine I can test this on, let me know if there's any issues with getting this working and I'll try to sort it out.

https://github.com/drislands/android-messages-desktop/releases/tag/411-fix.1

**Comment by Vilacard** [comment]
Thanks! I installed it and I am able to successfully login.

**Comment by maelchiotti** [comment]
Thank you! I will try it tomorrow to confirm if it's working.

**Comment by maelchiotti** [comment]
@drislands Worked perfectly, thank you so much
