### ISSUE TITLE
Contact List Source

### ISSUE THREAD

**Issue by briandmiller** [OrangeDrangon/android-messages-desktop#444]
Thanks for building and sharing this app. It installed and connected on my windows pc just fine.
My question is does the app use the address book of the gmail account that I am connected to in the app or does it sync with the address book in use on my phone which is my Office365 address book.
Either one is fine with me. I am just wanting to figure out the best way to stay in sync between this app and my phone.
Thanks agian

**Comment by innesst** [comment]
This app does not use any contact list. It only is a portal to messages.google.com/web which in turn is a portal to the Google messages app on your phone. This app sees only what the app on your phone sees. On my phone, I can see both Gmail and my personal Office contacts, but I have to manually import the exchange global address book into my personal Outlook address book to be able to see them on my phone.
