### ISSUE TITLE
Name not found

### ISSUE THREAD

**Issue by rymar1** [OrangeDrangon/android-messages-desktop#445]
In the panel icon whenever I open it it used to show the names of the past couple of contacts. Lately I get a name not found instead. I use Linux mint 21.3 Cinnamon.. This isn't an earth shattering issue as a minor annoyance.

**Comment by MattMski** [comment]
Having the same issue on my end

**Comment by Lancaban** [comment]
Same here, only started semi-recently

**Comment by OrangeDrangon** [comment]
Will be fixed in latest release
