### ISSUE TITLE
No tray icon Arch + Plasma 6.1.1 wayland

### ISSUE THREAD

**Issue by HighValueWarrior** [OrangeDrangon/android-messages-desktop#453]
**Describe the bug**
No tray icon after Plasma 6.1 - program operating and can be called up manually but no notifications/tray icon.

**To Reproduce**
Install anroid-messages-desktop-bin
pair with phone successful
upon close there is no tray icon
Go to tray entries - NO entry in list for android messages

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux 6.9..7-1
 - Plasma 6.1.1

Works correctly in x11

**Comment by HighValueWarrior** [comment]
Fixed by installing pkg libappindicator-gtk3
Needed for proper wayland operation.

**Comment by scoronado12** [comment]
Hi @HighValueWarrior - Did you install via AUR? I would ask the maintainer of the AUR package to add that as an optional dependency at a minimum. 

https://aur.archlinux.org/packages/android-messages-desktop-bin

**Comment by HighValueWarrior** [comment]
Yes via AUR.
I mentioned it on there, https://aur.archlinux.org/packages/android-messages-desktop  but I did not recieve an answer.
Perhaps a word from you might be helpful.
