### ISSUE TITLE
Option to have Window close Button instead to Minimize to the System Tray

### ISSUE THREAD

**Issue by WoofGrrrr** [OrangeDrangon/android-messages-desktop#467]
I sometimes click the window Close Button, when I meant instead minimize.

Could you add an option to have this instead to minimize to the System Tray?

**Comment by OrangeDrangon** [comment]
If the tray icon is enabled and you click close it goes to system tray at least on the platforms I use.

**Comment by WoofGrrrr** [comment]
I don't know what was going on, but what you say is true now.

It is working as you have said.  But then I just installed 5.5.0 as well.

Maybe that fixed some setting somewhere that got corrupted.

Sorry about the confusion.
