### ISSUE TITLE
Set urgency hint on new messages

### ISSUE THREAD

**Issue by aliveinadream** [OrangeDrangon/android-messages-desktop#62]
**Is your feature request related to a problem? Please describe.**
I have to check the app to see if there is new messages, instead of knowing from a highlighted window

**Describe the solution you'd like**
Window urgency hint was set on new messages.

**Additional context**
I'm using i3 on linux. I made a simple change but I don't think it is comprehensive

[urgency-hint.txt](https://github.com/OrangeDrangon/android-messages-desktop/files/4978053/urgency-hint.txt)

**Comment by OrangeDrangon** [comment]
Sorry for the long delay. I would be happy to merge this. I am not super familiar on how to apply patches. If you could either open a pull request or point me in the direction of a good guide I would be grateful.

Thanks
