### ISSUE TITLE
Notification Dot

### ISSUE THREAD

**Issue by mstras** [OrangeDrangon/android-messages-desktop#71]
Is it possible to have the icon on taskbar flash and or add a notification dot, it would be extremely helpful

**Comment by OrangeDrangon** [comment]
I will look into this in the coming days. I would also be happy to merge a pull request if you wanted to attempt to tackle this.

**Comment by mstras** [comment]
Thanks for everything.

I wish I had the know-how to do it or I would absolutely get my hands dirty.

**Comment by mstras** [comment]
I think this is back. New messages are not flashing the application icon.
